// Generated by https://quicktype.io

import * as cuid2 from '@paralleldrive/cuid2';
import * as cuid from 'cuid';

export interface Basket {
  id: string;
  items: BasketItem[];
}

export interface BasketItem {
  id: number;
  productName: string;
  price: number;
  quantity: number;
  pictureUrl: string;
  brand: string;
  type: string;
}

export class Basket implements Basket {
  constructor() {
    this.id = cuid2.createId();
    this.items = [];
  }

  id: string;
  items: BasketItem[];
}

export interface BasketTotals {
  shipping: number;
  subtotal: number;
  total: number;
}
